library(renv)
renv::init()
renv::install('devtools')
renv::install('tidyverse')
renv::install('readxl')
renv::install('readODS')
renv::install('rvest')
renv::install("igraph", type="binary")
renv::install('jbkunst/highcharter')
renv::install('ropensci/geojsonio')
renv::install('ggplot2')
renv::install('Greater-London-Authority/gglaplot')
renv::install('here')
renv::install('shinyglide')
renv::install('bslib')
renv::install('shinyjs')
renv::snapshot()
#renv::restore()



